prod_status:
  D019001: "PLANNED"
  D019002: "IN_PROGRESS"
  D019003: "COMPLETED"
  D019006: "CANCELLED"
  D019007: "ON_HOLD"

process_type:
  D014004: "MOTOR"
  D014002: "ROTOR"
  D014001: "STATOR"
  D014003: "CASE"
